version: '3.7'
services:
  php:
    container_name: moneto_php
    build:
      context: .
      dockerfile: docker/Dockefile
    volumes:
      - .:/var/www/html:cached
  nginx:
    container_name: moneto_nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:cached
    ports:
      - "80:80"
    depends_on:
      - php
