version: '3.7'
services:
  php:
    container_name: moneto_php
    build:
      context: .
      dockerfile: docker/Dockefile
    volumes:
      - .:/var/www/html:cached
  nginx:
    container_name: moneto_nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:cached
    ports:
      - "80:80"
    depends_on:
      - php
  storage:
    container_name: moneto_storage
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/mysql/mysql-innodb.conf:/etc/mysql/conf.d/innodb.conf
      - moneto_data:/var/lib/mysql
volumes:
  moneto_data:
